name: flutter_paystack_example
description: Demonstrates how to use the flutter_paystack plugin.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_paystack:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"